mode : overfit   # overfit / prune
seed : 0

dataset:
  train_samples : 30  # Per class
  test_samples  : 30  # Per class
  miss_samples  : 3   # Per class
  biased        : False  # True for biased dataset

model:
  type        : mlp  # mlp / transformer
  lr          : 0.001
  batch_size  : -1  # -1 for full batch
  hidden_dims : 32


prune:
  random_prune : False  # True for random pruning False for structured pruning
  num_prune    : 10     # Number of neurons to prune